substitutions:
  name: "m5-dial"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  fallback_wifi_password: "12345678"
  friendly_name: "M5 Dial"
  dashboard_package_import_url: github://ovettel/m5-dial-for-esphome/shys-m5-dial.yaml@main
  external_component_url: https://github.com/ovettel/m5-dial-for-esphome/

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: smarthomeyourself.m5_dial
    version: "1.0"
    
  platformio_options:
    lib_deps:
      - WiFi
      - SPI
      - FS
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified@0.1.14
      - m5stack/M5Dial

external_components:
  - source:
      type: git
      url:  ${external_component_url}
      ref: main
    components: [shys_m5_dial]
 
dashboard_import:
  package_import_url: ${dashboard_package_import_url}
  import_full_config: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:
  level: DEBUG
  
api:
  encryption:
    key: ${api_encryption_key}

ota:
  - platform: esphome
    password: ${ota_password}

improv_serial:
captive_portal:

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: ${fallback_wifi_password}
